### ISSUE TITLE
Throws error if used through the CLI without using the plugin 

### ISSUE THREAD

**Issue by dbettini** [shlomiassaf/ngc-webpack#11]
At the moment, it's impossible to run the CLI without instantiating the plugin. A `Cannot read property 'options' of undefined` error is being thrown.

**Comment by dlevkov** [comment]
Hello all, got this error suddenly

`
> ngc-w -p tsconfig.webpack.json "--webpack" "config/webpack.prod.js"

TypeError: Cannot read property 'options' of undefined
    at new WebpackChainModuleResolutionHostAdapter (D:\Angular2\TenTvApp\node_modules\src\webpack-chain-module-resolution-host-adapter.ts:12:119)
    at D:\Angular2\TenTvApp\node_modules\src\main.ts:19:46
    at Object.main (D:\Angular2\tools\@angular\tsc-wrapped\src\main.ts:60:12)
    at runInternal (D:\Angular2\TenTvApp\node_modules\src\main.ts:25:10)
    at main (D:\Angular2\TenTvApp\node_modules\src\main.ts:45:10)
    at Object.<anonymous> (D:\Angular2\TenTvApp\node_modules\src\main.ts:66:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
Compilation failed
` 
Don't have an idea what to do next, any help, plz.

Maybe some global package is missing? Or webpack plugin?

**Comment by dbettini** [comment]
@dlevkov It's a bug. I fixed it in #12 , but there's no word from @shlomiassaf yet.
