### ISSUE TITLE
Error "callback(): The callback was already called" when building with the new cleanup loader

### ISSUE THREAD

**Issue by pglazkov** [shlomiassaf/ngc-webpack#26]
After I added the `ngc-webpack` loader I get the following error during AOT build:

```
Error: callback(): The callback was already called.                                                       
   at context.callback (<project_path>\node_modules\loader-runner\lib\LoaderRunner.js:106:10)                                
   at Object.aotCleanLoader (<project_path>\node_modules\src\aot-clean-transformer\loader\text-based-loader\loader.ts:283:9) 
   at Object.aotCleanLoader (<project_path>\node_modules\src\aot-clean-transformer\loader\index.ts:16:31)                    
   at LOADER_EXECUTION (<project_path>\node_modules\loader-runner\lib\LoaderRunner.js:119:14)                                
   at runSyncOrAsync (<project_path>\node_modules\loader-runner\lib\LoaderRunner.js:120:4)                                   
   at iterateNormalLoaders (<project_path>\node_modules\loader-runner\lib\LoaderRunner.js:229:2)                             
   at iterateNormalLoaders (<project_path>\node_modules\loader-runner\lib\LoaderRunner.js:218:10)                            
   at <project_path>\node_modules\loader-runner\lib\LoaderRunner.js:233:3                                                    
   at Object.context.callback (<project_path>\node_modules\loader-runner\lib\LoaderRunner.js:111:13)                         
   at Object.module.exports (<project_path>\node_modules\angular2-template-loader\index.js:56:10)                            
   at LOADER_EXECUTION (<project_path>\node_modules\loader-runner\lib\LoaderRunner.js:119:14)                                
   at runSyncOrAsync (<project_path>\node_modules\loader-runner\lib\LoaderRunner.js:120:4)                                   
   at iterateNormalLoaders (<project_path>\node_modules\loader-runner\lib\LoaderRunner.js:229:2)                             
   at Array.<anonymous> (<project_path>\node_modules\loader-runner\lib\LoaderRunner.js:202:4)                                
   at Storage.finished (<project_path>\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:40:15)
   at <project_path>\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:77:9                    
   at <project_path>\node_modules\graceful-fs\graceful-fs.js:78:16                                                           
   at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)                                                                                   
```

**Comment by shlomiassaf** [comment]
Well, [it's a bug](https://github.com/shlomiassaf/ngc-webpack/blob/master/src/aot-clean-transformer/loader/text-based-loader/loader.ts#L281-L283) no doubt :)

I'll fix it but you do have errors there :)

**Comment by shlomiassaf** [comment]
Also publish 3.2.1

**Comment by pglazkov** [comment]
Right, after your fix, I don't see the error above, but I do see the errors you're referring to. However, I cannot find the source of the errors because they look like this:

```
ERROR in <path>/main.browser.aot.ts                                                                                             
(Emitted value instead of an instance of Error) Object literal's property 'xxx' implicitly has an 'any' type.                                  
NonErrorEmittedError: (Emitted value instead of an instance of Error) Object literal's property 'xxx' implicitly has an 'any' type.            
    at Object.emitError (<project_path>\node_modules\webpack\lib\NormalModule.js:121:14)                                      
    at Object.aotCleanLoader (<project_path>\node_modules\src\aot-clean-transformer\loader\text-based-loader\loader.ts:282:14)
    at Object.aotCleanLoader (<project_path>\node_modules\src\aot-clean-transformer\loader\index.ts:16:31)  _        
``` 
Also, I didn't have those errors before upgrading `ngc-webpack` and adding the new loader.

**Comment by shlomiassaf** [comment]
The loader has it's own TypeScript compilations process which loads from the `tsconfig` you supply in the plugin or specifically via `tsConfigPath` option.

It looks like it has no implicit any set to true...

**Comment by pglazkov** [comment]
Yes, that's correct, `noImplicitAny` is set to `true`. Is it not supported? Do you have any suggestions for a workaround?

**Comment by shlomiassaf** [comment]
Maybe i'm not getting it right...

But if you set `noImplicitAny` to `true` you can't have an implicit  type... 
it looks like `xxx` has an implicit type in `main.browser.aot.ts`

**Comment by pglazkov** [comment]
I get a lot of those errors and each of them says `in main.browser.aot.ts`...  This file is an entry point and `xxx` name is not present in that file, so the real stack trace is missing from the error. But missing stack trace is not really the issue here. The issue is why do I get errors at all? Everything was compiling and worked fine until I updated `ngc-webpack` and added the new cleanup loader, so I don't expect that the issue is with my code and the `noImplicitAny` setting...

**Comment by shlomiassaf** [comment]
The cleanup loader has it's own type checker, it must have this so it will transfer valid typescript to the next loader in chain, which is usually `awesome-typescript-loader` or `ts-loader`.

Maybe one of the files fails in the typecheckr, I'll need a sample, something I can reproduce and debug.

Also would like to point out that indeed there's no stack trace and I will check that but the loader [does not process ngfactory.ts](https://github.com/shlomiassaf/ngc-webpack/blob/master/src/aot-clean-transformer/loader/text-based-loader/loader.ts#L217) files which your `main.browser.aot.ts` probably references so it's pretty strange.

**Comment by pglazkov** [comment]
Unfortunately, I cannot reproduce it on a small sample project. I suppose I will have to wait for the TypeScript transformer to be ready before updating `ngc-webpack`...

**Comment by shlomiassaf** [comment]
You can update just don't use the loader

**Comment by pglazkov** [comment]
Isn't `resourceOverride` removed in the latest version?

**Comment by shlomiassaf** [comment]
it's there just not used in the starter.

I think... dont rememebr i'll check later
