### ISSUE TITLE
Angular 5.0.0.rc6

### ISSUE THREAD

**Issue by MADzO** [shlomiassaf/ngc-webpack#33]
I am getting this error with this version of angular:

> webpack-chain-module-resolution-host-adapter.js:7
        extendStatics(d, b);
TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at __extends (..\node_modules\ngc-webpack\src\webpack-chain-module-resolution-host-adapter.js:7:9)
    at ..\node_modules\src\webpack-chain-module-resolution-host-adapter.ts:7:62
    at Object.<anonymous> (..\node_modules\src\webpack-chain-module-resolution-host-adapter.ts:7:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (..\node_modules\src\main.ts:14:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C..\node_modules\src\plugin.ts:3:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)

**Comment by bartholomej** [comment]
Same here.
Actually this error starts from Angular `5.0.0-rc.4` [(changelog)](https://github.com/angular/angular/blob/master/CHANGELOG.md#500-rc4-2017-10-24). Versions before were OK.
Perhaps this information will help you @shlomiassaf ...

**Comment by giampierobono** [comment]
Same here with rc.8 :( 

@bartholomej I tried with rc.3 and I got this error:
`TypeError: compiler_cli_1.NgcCliOptions is not a constructor`

Do you have a workaround for this? Thanks :)

**Comment by shlomiassaf** [comment]
This is due to a breaking change in angular 5.x.x

I didn't rush into it because it's still RC but it looks like it's coming fast so i'll review the issue and see what can be done.

**Comment by giampierobono** [comment]
@shlomiassaf Sure no problem! You are doing a great job and your webpack plugins are incredibly amazing :) 

I was just wondering if @bartholomej managed to make it work with some version of Angular 5. I am struggling with the AOT build for Angular 5

**Comment by bartholomej** [comment]
Ok, to be clear - this issue was originally about JIT error message ;)

So, you can use `ngc-webpack` up to rc.3 with JIT compilation (usually in dev mode) but with AOT compilation it doesn't work at all for any Angular 5 version, as you said @giampierobono

**Comment by pdenomme** [comment]
how do you get it working with rc.3?  I'm still getting build errors with it.

**Comment by shlomiassaf** [comment]
The discussion for this topic is in #32, please read [this comment](https://github.com/shlomiassaf/ngc-webpack/issues/32#issuecomment-341276068) and help me by providing input.

Thanks.
