### ISSUE TITLE
Angular 5 Issue

### ISSUE THREAD

**Issue by REPTILEHAUS** [shlomiassaf/ngc-webpack#35]
Im working on a legacy project, just updated it from Angular 4.x to 5 and im running into this error which im unsure of, any ideas

```
[nodemon] starting `ts-node server.ts`

/Applications/MAMP/htdocs/username/Development/legacy-app/node_modules/ngc-webpack/src/webpack-chain-module-resolution-host-adapter.js:7
        extendStatics(d, b);
        ^
TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at __extends (/Applications/MAMP/htdocs/username/Development/legacy-app/node_modules/ngc-webpack/src/webpack-chain-module-resolution-host-adapter.js:7:9)
    at /Applications/MAMP/htdocs/username/Development/legacy-app/node_modules/src/webpack-chain-module-resolution-host-adapter.ts:7:62
    at Object.<anonymous> (/Applications/MAMP/htdocs/username/Development/legacy-app/node_modules/src/webpack-chain-module-resolution-host-adapter.ts:7:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Applications/MAMP/htdocs/username/Development/legacy-app/node_modules/src/main.ts:14:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by dmcclureagl** [comment]
See https://github.com/shlomiassaf/ngc-webpack/issues/32 very detailed description on why its not working and potentially a solution to migrate to the official ngtools solution.

**Comment by shlomiassaf** [comment]
Fixed with version 4
