### ISSUE TITLE
Angular 7 ngc-webpack 

### ISSUE THREAD

**Issue by mukulstan** [shlomiassaf/ngc-webpack#51]
hi,i am migrating my angular 4 admin project to 7 ,and after migration getting this error.The project was working fine with version4.

Cannot read property 'prototype' of undefined
    at __extends (/var/www/html/ifta_7/admin/node_modules/ngc-webpack/src/webpack-chain-module-resolution-host-adapter.js:5:69)
    at /var/www/html/ifta_7/admin/node_modules/src/webpack-chain-module-resolution-host-adapter.ts:7:62
    at Object.<anonymous> (/var/www/html/ifta_7/admin/node_modules/src/webpack-chain-module-resolution-host-adapter.ts:7:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/html/ifta_7/admin/node_modules/src/main.ts:15:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/html/ifta_7/admin/node_modules/src/plugin.ts:3:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
devDependancy:{
"webpack": "2.3.3",
    "webpack-dev-middleware": "1.10.1",
    "webpack-dev-server": "2.4.2",
    "webpack-dll-bundles-plugin": "1.0.0-beta.5",
    "webpack-merge": "4.1.0",
}

"ngc-webpack": "^1.2.0"
I have tried to upgrade version of ngc-webpack to 4.But then getting error @ngtools/webpack  not found

**Comment by ramya0311** [comment]
@mukulstan were you able to resolve this error?
